const API='https://bahisafety.com/demo/wp-json/wc/store/v1';
const state={cats:[],products:[],page:1,done:false,cart:JSON.parse(localStorage.getItem('bahi_cart')||'[]'),light:[],lightIndex:0};

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function strip(s){const d=document.createElement('div');d.innerHTML=s||'';return d.textContent||d.innerText||''}
function money(p){if(!p)return 'السعر عند الطلب';const n=Number(p.price||0)/(10**Number(p.currency_minor_unit??2));return n.toLocaleString('ar-SA',{maximumFractionDigits:Number(p.currency_minor_unit??2)})+' '+(p.currency_symbol||'')}
async function get(url){const r=await fetch(API+url,{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
function catFallback(n){const x=(n||'').toLowerCase();if(x.includes('حريق'))return'https://images.unsplash.com/photo-1518391846015-55a9cc003b25?auto=format&fit=crop&w=900&q=82';if(x.includes('طرق'))return'https://images.unsplash.com/photo-1513828583688-c52646db42da?auto=format&fit=crop&w=900&q=82';if(x.includes('حذ'))return'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=82';if(x.includes('قف'))return'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=900&q=82';return'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=900&q=82'}
function productImg(p){return p?.images?.[0]?.src||''}
function catCard(c){const image=c.image?.src||catFallback(c.name);return`<a class="cat" href="#category-${c.id}"><img src="${esc(image)}" alt="${esc(c.name)}" loading="lazy" onerror="this.src='${catFallback(c.name)}'"><div class="cat-text">${esc(c.name)}<small>${Number(c.count||0)} منتج</small></div></a>`}
function productCard(p){const image=productImg(p);return`<article class="product"><a class="pic" href="#product-${p.id}">${image?`<img src="${esc(image)}" alt="${esc(p.name)}" loading="lazy" decoding="async">`:`<div class="empty">لا توجد صورة</div>`}</a><div class="product-body"><div class="catname">${esc(p.categories?.[0]?.name||'مستلزمات السلامة')}</div><h3>${esc(p.name)}</h3><div class="price">${money(p.prices)}</div><div class="prod-actions"><button class="buy" data-add="${p.id}">أضف للسلة</button><a href="#product-${p.id}">التفاصيل</a></div></div></article>`}
function renderCats(){const h=state.cats.map(catCard).join('');$('#homeCats').innerHTML=h||'<div class="empty">لا توجد أقسام منشورة.</div>';$('#allCats').innerHTML=h||'<div class="empty">لا توجد أقسام منشورة.</div>'}
async function loadCats(){try{state.cats=await get('/products/categories?per_page=100&hide_empty=false');renderCats()}catch(e){console.error(e);$('#homeCats').innerHTML='<div class="empty">تعذر تحميل الأقسام من WooCommerce.</div>';$('#allCats').innerHTML=$('#homeCats').innerHTML}}
async function loadProducts(reset=false){if(reset){state.page=1;state.products=[];state.done=false;$('#productsGrid').innerHTML='<div class="loading">جاري التحميل...</div>'}if(state.done)return;try{const data=await get(`/products?per_page=20&page=${state.page}&orderby=date&order=desc`);if(!Array.isArray(data)||!data.length){state.done=true;$('#more').style.display='none';if(!state.products.length)$('#productsGrid').innerHTML='<div class="empty">لا توجد منتجات.</div>';return}state.products.push(...data);state.page++;state.done=data.length<20;$('#productsGrid').innerHTML=state.products.map(productCard).join('');$('#featured').innerHTML=state.products.slice(0,8).map(productCard).join('');bindProductButtons();$('#more').style.display=state.done?'none':'block'}catch(e){console.error(e);if(!state.products.length)$('#productsGrid').innerHTML='<div class="empty">تعذر تحميل المنتجات من WooCommerce.</div>'}}
function bindProductButtons(){$$('[data-add]').forEach(b=>b.onclick=e=>{e.preventDefault();const p=state.products.find(x=>String(x.id)===String(b.dataset.add));if(p){state.cart.push(p);localStorage.setItem('bahi_cart',JSON.stringify(state.cart));updateCart();toast('تمت إضافة المنتج إلى السلة')}})}
async function showCat(id){const c=state.cats.find(x=>String(x.id)===String(id));$('#catTitle').textContent=c?.name||'القسم';$('#catProducts').innerHTML='<div class="loading">جاري تحميل منتجات القسم...</div>';try{const d=await get(`/products?category=${encodeURIComponent(id)}&per_page=100`);$('#catProducts').innerHTML=d.map(productCard).join('')||'<div class="empty">لا توجد منتجات في هذا القسم.</div>';state.products=[...state.products,...d.filter(x=>!state.products.some(y=>y.id===x.id))];bindProductButtons()}catch(e){console.error(e);$('#catProducts').innerHTML='<div class="empty">تعذر تحميل منتجات القسم.</div>'}}
async function showProduct(id){$('#detail').innerHTML='<div class="loading">جاري تحميل المنتج...</div>';try{const p=await get('/products/'+id);const imgs=p.images||[];state.light=imgs.map(x=>x.src);state.lightIndex=0;const main=imgs[0]?.src||'';$('#detail').innerHTML=`<div class="detail-grid"><div class="gallery"><div class="main-image"><img id="mainImg" src="${esc(main)}" alt="${esc(p.name)}"></div><div class="thumbs">${imgs.map((im,i)=>`<button data-thumb="${i}" class="${i===0?'active':''}"><img src="${esc(im.src)}" alt=""></button>`).join('')}</div></div><div class="detail-info"><div class="catname">${esc(p.categories?.[0]?.name||'مستلزمات السلامة')}</div><h1>${esc(p.name)}</h1><div class="price">${money(p.prices)}</div><p>${esc(strip(p.description||p.short_description||''))}</p><div class="btns"><button class="btn primary" id="detailAdd">أضف للسلة</button><a class="btn whatsapp" href="https://wa.me/967773133380?text=${encodeURIComponent('السلام عليكم، أريد الاستفسار عن: '+p.name)}" target="_blank" rel="noopener">واتساب</a></div></div></div>`;$('#mainImg').onclick=()=>openLight(0);$$('[data-thumb]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.thumb);$('#mainImg').src=imgs[i].src;$$('[data-thumb]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});$('#detailAdd').onclick=()=>{state.cart.push(p);localStorage.setItem('bahi_cart',JSON.stringify(state.cart));updateCart();toast('تمت إضافة المنتج إلى السلة')}}catch(e){console.error(e);$('#detail').innerHTML='<div class="empty">تعذر تحميل تفاصيل المنتج.</div>'}}
function openLight(i){if(!state.light.length)return;state.lightIndex=i;$('#lightImage').src=state.light[i];$('#lightbox').classList.add('show');document.body.style.overflow='hidden'}
function closeLight(){ $('#lightbox').classList.remove('show');document.body.style.overflow=''}
function route(){const h=location.hash||'#home';$$('.page').forEach(x=>x.classList.remove('active'));if(h.startsWith('#category-')){$('#category').classList.add('active');showCat(h.split('-')[1])}else if(h.startsWith('#product-')){$('#product').classList.add('active');showProduct(h.split('-')[1])}else{const el=$(h)||$('#home');el.classList.add('active');if(h==='#products'&&!state.products.length)loadProducts(true)}closeDrawer();window.scrollTo({top:0,behavior:'smooth'})}
function closeDrawer(){$('#drawer').classList.remove('open');$('#backdrop').classList.remove('show')}
function updateCart(){$('#cartCount').textContent=state.cart.length}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2000)}
$('#menuOpen').onclick=()=>{$('#drawer').classList.add('open');$('#backdrop').classList.add('show')};$('#menuClose').onclick=closeDrawer;$('#backdrop').onclick=closeDrawer;
$('#searchOpen').onclick=()=>{location.hash='#products';setTimeout(()=>$('#productSearch').focus(),200)}
$('#cartOpen').onclick=()=>toast('عدد المنتجات في السلة: '+state.cart.length);
$('#more').onclick=()=>loadProducts(false);
document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>{if(history.length>1)history.back();else location.hash='#home'});
$('#productSearch').oninput=e=>{const q=e.target.value.trim().toLowerCase();if(!q){$('#productsGrid').innerHTML=state.products.map(productCard).join('')}else{$('#productsGrid').innerHTML=state.products.filter(p=>p.name.toLowerCase().includes(q)).map(productCard).join('')}bindProductButtons()};
$('#sort').onchange=e=>{const a=[...state.products],v=e.target.value;if(v==='title')a.sort((x,y)=>x.name.localeCompare(y.name,'ar'));if(v==='price')a.sort((x,y)=>Number(x.prices?.price||0)-Number(y.prices?.price||0));if(v==='-price')a.sort((x,y)=>Number(y.prices?.price||0)-Number(x.prices?.price||0));$('#productsGrid').innerHTML=a.map(productCard).join('');bindProductButtons()};
$('#lightClose').onclick=closeLight;$('#lightbox').onclick=e=>{if(e.target.id==='lightbox')closeLight()};$('#lightPrev').onclick=()=>{state.lightIndex=(state.lightIndex-1+state.light.length)%state.light.length;$('#lightImage').src=state.light[state.lightIndex]};$('#lightNext').onclick=()=>{state.lightIndex=(state.lightIndex+1)%state.light.length;$('#lightImage').src=state.light[state.lightIndex]};
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeLight()});window.addEventListener('hashchange',route);
updateCart();loadCats();loadProducts(true);route();
