const API='https://bahisafety.com/wp-json/wc/store/v1';
const WA='967773133380';
const state={cats:[],products:[],localCats:[],localProducts:[],page:1,loading:false,done:false,query:'',sort:'date',cart:JSON.parse(localStorage.getItem('bahi_cart')||'[]'),usingLocal:false};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function money(p){const x=p?.prices;if(x?.price){const n=Number(x.price)/10**(x.currency_minor_unit||2);return `${n.toLocaleString('ar-SA')} ${x.currency_symbol||''}`.trim()}return (p?.price_html||'').replace(/<[^>]*>/g,'')||'السعر عند الطلب'}
function imgOf(p){return p?.images?.[0]?.src||''}
const CATEGORY_IMAGES={'احذ':'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=82','نظ':'https://images.unsplash.com/photo-1577803645773-f96470509666?auto=format&fit=crop&w=900&q=82','قف':'https://images.unsplash.com/photo-1591768793355-74d04bb6608f?auto=format&fit=crop&w=900&q=82','خو':'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=900&q=82','ملابس':'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=900&q=82','يلقات':'https://images.unsplash.com/photo-1521791055366-0d553872125f?auto=format&fit=crop&w=900&q=82','حريق':'https://images.unsplash.com/photo-1518391846015-55a9cc003b25?auto=format&fit=crop&w=900&q=82','طرق':'https://images.unsplash.com/photo-1545459720-aac8509eb02c?auto=format&fit=crop&w=900&q=82','حزام':'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=900&q=82','كمام':'https://images.unsplash.com/photo-1584634731339-252c581abfc5?auto=format&fit=crop&w=900&q=82'};
function categoryFallback(name){const n=String(name||'');for(const k in CATEGORY_IMAGES)if(n.includes(k))return CATEGORY_IMAGES[k];return 'assets/scene-construction.webp'}
function catImg(c){return c?.image?.src||categoryFallback(c?.name)}
function catCard(c){return `<article class="cat-card" data-cat="${c.id}"><img loading="lazy" decoding="async" src="${esc(catImg(c))}" alt="${esc(c.name)}" onerror="this.onerror=null;this.src='assets/scene-construction.webp'"><div class="cat-name">${esc(c.name)}<div class="cat-count">${Number(c.count||0)} منتج</div></div></article>`}
function productCard(p){const src=imgOf(p);return `<article class="product-card"><div class="pic" data-product="${p.id}">${src?`<img loading="lazy" decoding="async" src="${esc(src)}" alt="${esc(p.name)}" onerror="this.onerror=null;this.src='assets/scene-construction.webp'">`:`<img loading="lazy" src="assets/scene-construction.webp" alt="${esc(p.name)}">`}</div><div class="product-info"><div class="product-cat">${esc(p.categories?.[0]?.name||'مستلزمات السلامة')}</div><h3>${esc(p.name)}</h3><div class="price">${money(p)}</div><div class="product-actions"><button class="mini-btn primary" data-product="${p.id}">التفاصيل</button><button class="mini-btn" data-add="${p.id}">+ سلة</button></div></div></article>`}
async function fetchJSON(url,tries=2){let last;for(let i=0;i<tries;i++){try{const r=await fetch(url,{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.json()}catch(e){last=e;await new Promise(x=>setTimeout(x,350*(i+1)))}}throw last}
async function loadLocal(){try{const d=await fetch('assets/catalog.json',{cache:'force-cache'}).then(r=>r.json());state.localCats=d.categories||[];state.localProducts=d.products||[]}catch(e){state.localCats=[];state.localProducts=[]}}
function useLocal(){state.usingLocal=true;state.cats=state.localCats;state.products=state.localProducts.slice();state.page=1;state.done=true;renderCats();renderProducts();renderFeatured()}
async function loadCats(){
 try{const data=await fetchJSON(`${API}/products/categories?per_page=100&hide_empty=false`);if(Array.isArray(data)&&data.length){state.cats=data.filter(c=>!c.parent||c.parent===0);renderCats();return}}catch(e){console.warn('API categories unavailable; local catalog will be used',e)}
 state.cats=state.localCats;renderCats()
}
function renderCats(){const html=state.cats.map(catCard).join('')||'<div class="about-card">لا توجد أقسام حالياً.</div>';$('#homeCatGrid').innerHTML=html;$('#allCatGrid').innerHTML=html}
async function loadProducts(reset=false){
 if(state.usingLocal){renderProducts();renderFeatured();return}
 if(state.loading||state.done&&!reset)return;state.loading=true;if(reset){state.page=1;state.products=[];state.done=false;$('#productGrid').innerHTML=''}
 $('#loadMore').textContent='جاري التحميل...';
 try{const q=new URLSearchParams({page:state.page,per_page:20,order:'desc',orderby:state.sort==='date'?'date':state.sort==='price'?'price':'title'});if(state.query)q.set('search',state.query);const data=await fetchJSON(`${API}/products?${q}`);if(!Array.isArray(data)||!data.length)state.done=true;else{state.products.push(...data);state.page++;if(data.length<20)state.done=true;renderProducts();if(state.page===2)renderFeatured()}}
 catch(e){console.warn('API products unavailable; switching to local catalog',e);useLocal()}
 state.loading=false;$('#loadMore').textContent=state.done?'تم عرض كل المنتجات':'تحميل المزيد'
}
function renderProducts(){let a=[...state.products];if(state.query)a=a.filter(p=>String(p.name).toLowerCase().includes(state.query.toLowerCase()));if(state.sort==='title')a.sort((x,y)=>String(x.name).localeCompare(String(y.name),'ar'));if(state.sort==='price')a.sort((x,y)=>Number(x.prices?.price||0)-Number(y.prices?.price||0));if(state.sort==='-price')a.sort((x,y)=>Number(y.prices?.price||0)-Number(x.prices?.price||0));$('#productGrid').innerHTML=a.map(productCard).join('')||'<div class="about-card">لا توجد منتجات مطابقة.</div>'}
function renderFeatured(){const list=state.products.slice(0,8);$('#featuredGrid').innerHTML=list.map(productCard).join('')||'<div class="about-card">لا توجد منتجات لعرضها.</div>'}
async function categoryProducts(id,name){showView('category');$('#catTitle').textContent=name;$('#categoryGrid').innerHTML='<div class="about-card">جاري تحميل المنتجات...</div>';if(state.usingLocal){const data=state.localProducts.filter(p=>p.categories?.some(c=>String(c.id)===String(id)||c.name===name));$('#categoryGrid').innerHTML=data.map(productCard).join('')||'<div class="about-card">لا توجد منتجات منشورة في هذا القسم.</div>';return}try{const data=await fetchJSON(`${API}/products?category=${encodeURIComponent(id)}&per_page=100&page=1`);$('#categoryGrid').innerHTML=(data||[]).map(productCard).join('')||'<div class="about-card">لا توجد منتجات منشورة في هذا القسم.</div>'}catch(e){const data=state.localProducts.filter(p=>p.categories?.some(c=>String(c.id)===String(id)||c.name===name));$('#categoryGrid').innerHTML=data.map(productCard).join('')||'<div class="about-card">تعذر تحميل منتجات القسم حالياً.</div>'}}
async function productDetail(id){showView('product');$('#productDetail').innerHTML='<div class="about-card">جاري تحميل المنتج...</div>';let p;try{if(!state.usingLocal)p=await fetchJSON(`${API}/products/${encodeURIComponent(id)}`)}catch(e){}if(!p)p=state.localProducts.find(x=>String(x.id)===String(id));if(!p){$('#productDetail').innerHTML='<div class="about-card">تعذر تحميل تفاصيل المنتج.</div>';return}const images=(p.images||[]).filter(x=>x?.src);const active=images[0]?.src||'assets/scene-construction.webp';$('#productDetail').innerHTML=`<div class="detail"><div class="detail-main"><div class="detail-gallery"><img id="mainProductImage" class="main-product-image" src="${esc(active)}" alt="${esc(p.name)}" loading="eager" decoding="async" onclick="openLightbox(this.src)"><div class="thumbs">${images.map((im,i)=>`<img class="${i===0?'active':''}" src="${esc(im.src)}" alt="${esc(im.alt||p.name)}" data-main="${esc(im.src)}" loading="lazy">`).join('')}</div></div><div><div class="product-cat">${esc(p.categories?.[0]?.name||'مستلزمات السلامة')}</div><h1>${esc(p.name)}</h1><div class="price">${money(p)}</div><div class="detail-desc">${p.description||p.short_description||'<p>لا يوجد وصف متاح.</p>'}</div><div class="product-actions"><button class="mini-btn primary" data-add="${p.id}">إضافة للسلة</button><a class="mini-btn wa" href="https://wa.me/${WA}?text=${encodeURIComponent('السلام عليكم، أريد الاستفسار عن: '+p.name)}" target="_blank" rel="noopener">واتساب</a></div><a class="btn ghost" href="${esc(p.permalink||'https://bahisafety.com/shop/') }" target="_blank" rel="noopener">عرض المنتج في الموقع</a></div></div></div>`;$$('.thumbs img').forEach(t=>t.onclick=()=>{const main=$('#mainProductImage');main.src=t.dataset.main;$$('.thumbs img').forEach(x=>x.classList.remove('active'));t.classList.add('active')})}
function showView(id,push=true){$$('.view').forEach(v=>v.classList.remove('active'));const el=$('#'+id);if(el)el.classList.add('active');closeDrawer();closeSearchModal();closeLightbox();window.scrollTo({top:0,behavior:'smooth'});if(push){const hash='#'+id;if(location.hash!==hash)history.pushState({id},'',hash)}}
function navigateTo(hash){if(location.hash===hash){parseHash();return}location.hash=hash}
function appBack(){if($('#lightbox').classList.contains('show')){closeLightbox();return}const raw=location.hash.slice(1)||'home';if(raw.startsWith('product=')){navigateTo('#products');return}if(raw.startsWith('category=')){navigateTo('#categories');return}if(raw==='category'||raw==='categories'||raw==='products'||raw==='about'){navigateTo('#home');return}if(history.length>1)history.back();else navigateTo('#home')}
function parseHash(){const raw=location.hash.slice(1)||'home';if(raw.startsWith('product=')){productDetail(raw.split('=')[1]);return}if(raw.startsWith('category=')){const id=raw.split('=')[1];const c=state.cats.find(x=>String(x.id)===String(id));categoryProducts(id,c?.name||'القسم');return}showView(raw,false)}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function closeDrawer(){$('#drawer').classList.remove('open');$('#backdrop').classList.remove('show')}function closeSearchModal(){$('#searchModal').classList.remove('show')}function openDrawer(){$('#drawer').classList.add('open');$('#backdrop').classList.add('show')}
function addCart(id){let p=state.products.find(x=>String(x.id)===String(id))||state.localProducts.find(x=>String(x.id)===String(id));if(!p){toast('تعذر العثور على المنتج');return}state.cart.push({id:p.id,name:p.name,price:money(p),image:imgOf(p)});localStorage.setItem('bahi_cart',JSON.stringify(state.cart));updateCart();toast('تمت إضافة المنتج إلى السلة')}
function updateCart(){$('#cartCount').textContent=state.cart.length}
function openLightbox(src){if(!src)return;$('#lightboxImg').src=src;$('#lightbox').classList.add('show');document.body.style.overflow='hidden'}
document.addEventListener('click',e=>{const cat=e.target.closest('[data-cat]');if(cat){navigateTo(`#category=${cat.dataset.cat}`);return}const prod=e.target.closest('[data-product]');if(prod){navigateTo(`#product=${prod.dataset.product}`);return}const add=e.target.closest('[data-add]');if(add){e.stopPropagation();addCart(add.dataset.add)}if(e.target.matches('[data-back]'))appBack()});
$('#menuBtn').onclick=openDrawer;$('#closeMenu').onclick=closeDrawer;$('#backdrop').onclick=closeDrawer;$('#searchBtn').onclick=()=>$('#searchModal').classList.add('show');$('#closeSearch').onclick=()=>$('#searchModal').classList.remove('show');$('#modalSearch').oninput=e=>{const q=e.target.value.trim().toLowerCase();const hits=state.products.filter(p=>String(p.name).toLowerCase().includes(q)).slice(0,10);$('#searchResults').innerHTML=hits.map(productCard).join('')};$('#loadMore').onclick=()=>loadProducts(false);$('#sortSelect').onchange=e=>{state.sort=e.target.value;renderProducts()};$('#searchInput').oninput=e=>{state.query=e.target.value.trim();renderProducts()};$('#cartBtn').onclick=()=>toast(`السلة تحتوي على ${state.cart.length} منتج`);function closeLightbox(){$('#lightbox').classList.remove('show');document.body.style.overflow=''}$('#closeLightbox').onclick=closeLightbox;$('#backFromLightbox').onclick=closeLightbox;$('#lightbox').onclick=e=>{if(e.target.id==='lightbox')closeLightbox()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#lightbox').classList.contains('show'))closeLightbox()});window.addEventListener('hashchange',parseHash);window.addEventListener('popstate',parseHash);
(async function init(){updateCart();await loadLocal();parseHash();await loadCats();await loadProducts(true)})();
